### ISSUE TITLE
ImportError: No Module named 'pwd'

### ISSUE THREAD

**Issue by danieleteti** [hozn/coilmq#20]
Hi,
Windows 10, Python 3.5. Installed Coilmq with pip. Running coilmq I get this error:

```
Traceback (most recent call last):
  File "C:\Python35\Scripts\coilmq-script.py", line 9, in <module>
    load_entry_point('CoilMQ==1.0.0', 'console_scripts', 'coilmq')()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python35\lib\site-packages\coilmq\start.py", line 10, in <module>
    import daemon as pydaemon
  File "c:\python35\lib\site-packages\daemon\__init__.py", line 42, in <module>
    from .daemon import DaemonContext
  File "c:\python35\lib\site-packages\daemon\daemon.py", line 25, in <module>
    import pwd
ImportError: No module named 'pwd'
```

**Comment by hozn** [comment]
Deferring to Alexander on this one.

**Comment by danieleteti** [comment]
Still present.

**Comment by ttreptow** [comment]
Any chance we could get a version with this fix pushed to pypi? Version 1.0.0 does not have it.

**Comment by ZhukovAlexander** [comment]
@danieleteti , @ttreptow , I've uploaded the latest version to PyPI, please, check. Also, in future prefer to install CoilMQ from github, as it will likely to have the most recent code and fixes.

**Comment by danieleteti** [comment]
OK thank you, the issue is fixed now.

**Comment by ttreptow** [comment]
@ZhukovAlexander Thanks for the quick turnaround
